id: IB8D27951
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:23:26+00:00'
last_modified: '2022-06-08T13:18:07.499753+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016296
  title: སྤྱི་འདུལ་རྟ་དབུ་དམར་ཆུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BA44:
      image_group_id: I00JW501359
      title: ''
      total_pages: 592
      order: 1
      base_file: BA44.txt
    C4D8:
      image_group_id: I00JW501360
      title: ''
      total_pages: 578
      order: 2
      base_file: C4D8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
