id: IB8D27951
legacy_id: P007024
ocr_import_info:
  bdrc_scan_id: W00EGS1016296
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T23:20:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:06:55.278949+00:00'
last_modified: 2022-08-30 21:08:31.443261
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016296
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016296
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱི་འདུལ་རྟ་དབུ་དམར་ཆུང་།
  author: བློ་གྲོས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.5568287529039645
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I00JW501360:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501360
      total_pages: 578
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00JW501360.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5425062654415456
    legacy_id: v002
  I00JW501359:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501359
      total_pages: 592
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00JW501359.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5751998034830766
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
