id: P007024
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016296
  title: སྤྱི་འདུལ་རྟ་དབུ་དམར་ཆུང
  author: ''
  volumes:
    ef715734b8f642dbb75dc9ad4606b871:
      image_group_id: I00JW501359
      title: ''
      volume_number: 1
      total_pages: 592
    b71dce0c1f364bb5a7bc5b3fcc64c8e4:
      image_group_id: I00JW501360
      title: ''
      volume_number: 2
      total_pages: 578
ebook_metadata:
  title: སྤྱི་འདུལ་རྟ་དབུ་དམར་ཆུང
  author: ''
  sku: P007024
  cover: cover.jpg
  layers:
  - pagination
